### ISSUE TITLE
dji_m100_description invalid tag

### ISSUE THREAD

**Issue by aravindSwamy94** [tahsinkose/dji_m100_gazebo#1]
Hi, 
       Great work... 
I have an issue when i compile and run the simulate.launch

Invalid <arg> tag: dji_m100_description
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/home/aravind/Desktop/Aalto_entry/Drone_Project/Gazebo_simulation/Catkin_WS_Gazebo/src
ROS path [2]=/opt/ros/kinetic/share. 

... 

I saw the launch file and it tries to find a package dji_m100_description. But that package is not given here. Can you please let me know where to find them as well.

**Comment by tahsinkose** [comment]
It is listed in the organization `dji-m100-ros`. Here is the [link](https://github.com/dji-m100-ros/dji_m100_description).

**Comment by aravindSwamy94** [comment]
Yup Thank you i found that and traversed in many packages. Do you have any Idea of the hector_quadrotor package and the errors linked to this??

1. ‘Vector3d’ is not a member of ‘gazebo::math’
                 math::Vector3d local_position = this->spherical_coordinates_handle->LocalFromSpherical(math::Vector3d(lat,lon,alt));

2.  error: ‘class gazebo::DJI_ROS_ControlPlugin’ has no member named ‘base_orientation’
                     this->base_orientation.z = quat_msg->quaternion.z
.
.
.
.
and many errors like this

I suppose these are some version errors. Im using version 7 and these packages are required to build the dji_m100_ros packages..

**Comment by tahsinkose** [comment]
When you solve the first one, the other will automatically disappear. Gazebo 7.0 uses `gazebo::math` namespace for math utilities and you may look to the respective API of Gazebo.
