### ISSUE TITLE
Automotic control command for dji-m100

### ISSUE THREAD

**Issue by aravindSwamy94** [tahsinkose/dji_m100_gazebo#2]
Hi,
          I tried launching the "start.launch" and "spawn_dji_m100.launch" . I was able to get the robot and its position through "robot_state_publisher". I need a help. Can we provide control input to the through any means. Like Matrice 100 usually takes in 4 control signals roll,pitch,yaw and altitude. Is there any way, we can give this input to the spawned robot in spawn_dji_m100.launch to have an automatic control

**Comment by tahsinkose** [comment]
Giving links to the questions is not a good practice, but this is not that formal repo either :smile: Follow the [Medium post](https://medium.com/@tahsincankose/implementing-dji-m100-emulator-in-ros-gazebo-for-hitl-e79f4bb077f6) I have written after developing these packages. It shows how to manipulate the robot using `rqt_gui`.

**Comment by aravindSwamy94** [comment]
Sorry .. But thanks anyways.
